### ISSUE TITLE
create zip file of demo data

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/mosviz#137]
Create a simple zip file with data that can be directly loaded into mosviz so users have a simple quick load dataset.

- [x] Find dataset we can share (@brechmos-stsci)
- [x] Find "permanent" location to store the data (@eteq)
- [x] Put dataset into "permanent location"
- [x] Update documentation with location

**Comment by kassin** [comment]
You are allowed to publicly release these data as long as you keep it to ~50 objects.  Please see the README files in each directory on central store for permissions for the other data sets.  I tried my best to get the authors to write whether they could be publicly released or not.

**Comment by eteq** [comment]
@kassin - the DEIMOS data are yours, right?  If we end up posting ~50 object subset on [Zenodo](https://zenodo.org/) do you want to be the one to do that so that it makes you officially the public "owner"?

**Comment by kassin** [comment]
I don't need to officially be the owner.  It's only a practice data set.  We will eventually replace it with something much better.  I'm hoping one of the product owners of the fall sprints will have a better data set.

**Comment by brechmos-stsci** [comment]
The deimos example dataset we have has 79 objects. @kassin may we zip it up and release as a test dataset for people who want to try out mosviz?

**Comment by kassin** [comment]
Yes 79 are fine to package and release.  Thought you had the full sample of 544.

**Comment by eteq** [comment]
More on the general problem of where data belongs at https://github.com/spacetelescope/style-guides/blob/master/guides/where-to-put-your-data.md#storage-locationplatform-for-non-archived-datasets .

Based on that I'd say the path of least resistance is to put the data on Zenodo.  To do that, go to https://zenodo.org/, and choose the "upload" button.  Then just fill in the form and include the zip file.  Once that's done, the result is a permanent (hopefully) link that you can point users to from the documentation.

**Comment by eteq** [comment]
One related but possibly a bit tangential thought:  if we also want to write some tests using this data (which is a good idea since it's what users will see...) a convenient choice is to use the astropy remote data machinery: http://docs.astropy.org/en/stable/utils/index.html#module-astropy.utils.data .  Note that tests using this should have a mark that makes it so they do *not* run automatically - the user/devs should be able to run tests even if they are offline or Zenodo is non-responsive.  In astropy this is easily done with the ``remote-data`` flag - I'm not sure if that's on or not in mosviz?

**Comment by brechmos-stsci** [comment]
Not yet. There is a ticket Nick is supposed to do for this sprint to get data up into artifactory for us to use for tests.

**Comment by brechmos-stsci** [comment]
I am going to close this ticket now as all the checkboxes have been fulfilled.
