### ISSUE TITLE
Check we can read level 2 and fake up level 3 JWST image.

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/mosviz#194]

**Comment by ibusko** [comment]
As far as I can tell, level 2 data seems to be read correctly. Although they may look a bit weird, certainly because it's made-up data. When I tried the 'merge' option, it looked like some extensions were dropped.

The level 3 cutouts seem OK as well. The level 3 s2d files seem to work as well, in the same way as level 2. The level 3 x1d spectra are displayed with the scatter plotter by default. When I tried to use specviz, it complained saying that it's not a 1D spectrum.

**Comment by ibusko** [comment]
Hmm.... now I realize I was probably just using glue to read and display the files. 

As for the level 2 table, glue can read it and display it as a table with the table viewer. But I can't see the mosviz viewer that is supposed to understand that table. Last time I tried it (a long ago) it was one of the viewer options provided in the drop down, wasn't it?

**Comment by ibusko** [comment]
My problems were related to a contaminated conda environment. I re-started it and now I can run mosviz with no problems. I confirm we can read level 2 and level 3 data.
