### ISSUE TITLE
MSA slitlet shapes displayed on cut-out images

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/mosviz#95]
Small question of how this is implemented and then another larger question of whether we can use https://github.com/astropy/regions as part of this functionality.

**Comment by javerbukh** [comment]
- Multiple slits
- Slits at different angles
- One tab/stack/drop down per slit

**Comment by robelgeda** [comment]
We should have yaml file that describes the slit shapes of instruments. This is assuming that the NIRSpec MSA is not the only instrument that will be supported by MOSViz. @kassin

**Comment by eteq** [comment]
@robelgeda - to clarify, part of the point of using `regions` is that that way we *don't* have to invent a new "standard" for defining regions. You can see in http://astropy-regions.readthedocs.io/en/latest/ that `regions` current supports `ds9` and `crtf` formats, and the idea is to eventually support the `VO` region standard.

That said, those are all regions in the sense of specific regions meaning a specific ra and dec for each slit.  If you were instead thinking we need to just say things like "NIRSpec slits are rectangles of length X width Y", then I agree that's necessary but I would advocate that being done first as a code-level standard, and only adding a specific file format if it turns out there's specific need for it. 

Or: always right the code *before* the standard, not vice versa :wink:

**Comment by robelgeda** [comment]
I agree, my idea is the "NIRSpec slits are rectangles of length X width Y" type of definitions.
